# Generated by Django 5.0 on 2024-01-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbschool', '0002_course_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('teacher_email', models.EmailField(max_length=254, unique=True)),
                ('teacher_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
    ]
